### ISSUE TITLE
Add --offline flag to update tool documentation

### ISSUE THREAD

**Issue by Aaquiff** [wso2/docs-updates#108] opened 2022-01-05 06:55 UTC
Description:
Location: https://updates.docs.wso2.com/en/latest/updates/update-tool

We need to add the flag --offline to the flags list for apply-hotfix command.

`--offline apply hotfix offline`

- https://updates.docs.wso2.com/en/latest/updates/update-commands/#wso2update_os62-apply-hotfix

**Comment by chamindi-a** [comment] 2022-02-07 07:53
Duplicate of #88

**Comment by chamindi-a** [comment] 2022-02-07 07:54
close #108

**Comment by chamindi-a** [comment] 2022-09-22 04:57
This content is changed thus the issue is fixed

**Closed** 2022-09-22 04:57 UTC
