### ISSUE TITLE
Doc Feedback:

### ISSUE THREAD

**Issue by ggianoglio** [wso2/docs-updates#22] opened 2021-01-18 11:23 UTC
Location : https://updates.docs.wso2.com/en/latest/updates/continuous-update/

The link in `Need to further refer WSO2 recommended Puppet and Ansible, Click Here.` https://updates.docs.wso2.com/en/latest/updates/updates/faq/#what-are-the-recommended-configuration-management-tools-to-deploy-configurations-to-client-nodes is broken (Page not found).

**Comment by chamindi-a** [comment] 2021-01-19 04:17
Thank you for your input, I have corrected this issue and a PR is being added

**Comment by chamindi-a** [comment] 2021-01-19 09:13
#21 has resolved the issue

**Comment by VimukthiPerera** [comment] 2021-03-05 21:25
Closing as the issue is resolved by #24

**Closed by VimukthiPerera** 2021-03-05 21:25 UTC
